### ISSUE TITLE
Running "python configure.py" fails

### ISSUE THREAD

**Issue by LexxLuey** [aellerton/demo-allauth-bootstrap#34]
I have been following the instructions in your README but have hit a dead end when trying to configure the project.

Running python configure.py throws the following error:

Traceback (most recent call last):
  File "/home/devops/Desktop/demo-allauth-bootstrap-master/configure.py", line 63, in <module>
    settings_template = get_template("settings.template.py")
  File "/home/devops/Desktop/demo-allauth-bootstrap-master/env/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: settings.template.py

**Comment by aellerton** [comment]
Can you copy in a full log of steps you did up to that point? (redact any
personal information or course)

**Comment by aellerton** [comment]
Hi there,

At first I was going to write that "configure.py" vs "./configure.py" shouldn't matter -- the "./" matters when running things because binaries will resolve from your `PATH`, but when finding a file, the shell will look in your current dir first.

Further, when I first tested it, I did it with a virtualenv in another directory, and it worked fine with "configure.py".

However, trying it with a virtualenv in the same directory, it didn't work. Very strange.

Side note: "env" is a program you can run; I don't trust there isn't a conflict when naming the virtualenv that, so probably don't use that name.

Can you try exactly the following:

```
cd demo-allauth-bootstrap
python3 -m venv mypy
. ./mypy/bin/activate
pip install -r requirements.txt
python ./configure.py
```

and send me the output?

In the meantime, I'll see if there's some reason that the "./" suddenly became a requirement.

**Comment by LexxLuey** [comment]
Yes I did the following and everything works fine. It only fails if I run the last line thus:

`python configure.py`
