### ISSUE TITLE
makemigrations does not pick up changes to UserProfile model

### ISSUE THREAD

**Issue by djchou** [aellerton/demo-allauth-bootstrap#5]
Hi, I'm relatively new to django.  I'm just curious why manage.py makemigrations does not pick up changes to the UserProfile model.  Is there another command that i should be using (syncdb didnt pick up changes either).

**Comment by aellerton** [comment]
Hi there,

I don't know why but all the django projects I've seen are the same. I googled around and the only things I can find are comments about [initial migrations](http://stackoverflow.com/questions/24969471/django-polls-tutorial-no-changes-detected-in-app-polls), which isn't the problem here. 

My "solution" during development is to run "make rebuild". I like this in development because it forces a clean and complete setup process, but I concede that as a project gets bigger and is in production, migrate needs to work ;)

As it stands this isn't a bug in the demo so I'll close this.

**Comment by djchou** [comment]
I wonder if this is a symptom of how the make file initially creates the database using syncdb.  Shouldn't it be created using makemigrations / migrate?
